<?php

namespace App\JsonApi\V2\Items;

use App\Enums\ItemStatus;
use Illuminate\Validation\Rule;
use LaravelJsonApi\Laravel\Http\Requests\ResourceRequest;
use LaravelJsonApi\Validation\Rule as JsonApiRule;

class ItemRequest extends ResourceRequest
{
    /**
     * Get the validation rules for the resource.
     *
     * @return array
     */
    public function rules(): array
    {
        if ($this->model()) {
            return [
                'name'           => ['sometimes', 'string'],
                'status'         => ['sometimes', Rule::in(collect(ItemStatus::cases())->pluck('value')->toArray())],
                'excerpt'        => ['sometimes', 'string'],
                'description'    => ['sometimes', 'string', 'nullable'],
                'image'          => ['sometimes', 'nullable', 'url'],
                'is_on_homepage' => ['sometimes', 'boolean'],
                'date_at'        => ['sometimes', 'date_format:Y-m-d'],
                'category'       => ['sometimes', JsonApiRule::toOne()],
                'tags'           => ['sometimes', JsonApiRule::toMany()],
                'user'           => ['sometimes', 'nullable', JsonApiRule::toOne()],
            ];
        }

        return [
            'name'           => ['required', 'string'],
            'status'         => ['required', Rule::in(collect(ItemStatus::cases())->pluck('value')->toArray())],
            'excerpt'        => ['required', 'string'],
            'description'    => ['string', 'nullable'],
            'image'          => ['nullable', 'url'],
            'is_on_homepage' => ['required', 'boolean'],
            'date_at'        => ['required', 'date_format:Y-m-d'],
            'category'       => ['required', JsonApiRule::toOne()],
            'tags'           => ['required', JsonApiRule::toMany()],
            'user'           => ['sometimes', 'nullable', JsonApiRule::toOne()],
        ];
    }

    public function isCreating(): bool
    {
        return parent::isCreating(); // TODO: Change the autogenerated stub
    }
}
